# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diantre < Formula
  desc ""
  homepage "https://github.com/mericozkayagan/diantre"
  version "0.0.9"

  on_macos do
    url "https://github.com/mericozkayagan/diantre/releases/download/v0.0.9/diantre_0.0.9_darwin_all.tar.gz"
    sha256 "46439600a112c2ad537725bc8ab5ab91ea206acfe320fdaddb977159b5179a01"

    def install
      bin.install "diantre"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mericozkayagan/diantre/releases/download/v0.0.9/diantre_0.0.9_linux_arm64.tar.gz"
      sha256 "0a4f094b00fa2f60435464c78c2f9731ee6057e0993854e2b98986ea68f9025a"

      def install
        bin.install "diantre"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mericozkayagan/diantre/releases/download/v0.0.9/diantre_0.0.9_linux_amd64.tar.gz"
      sha256 "3cca97545f1698e4f52155645cd1e543efb4acfb524585595c43def220130a67"

      def install
        bin.install "diantre"
      end
    end
  end
end
