# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minecraft < Formula
  desc ""
  homepage "https://github.com/mericozkayagan/minecraft"
  version "0.0.1"

  on_macos do
    url "https://github.com/mericozkayagan/minecraft/releases/download/v0.0.1/minecraft_0.0.1_darwin_all.tar.gz"
    sha256 "510df91b32d414e8e0c8b22b85117fab695681997f3bbd91d7025fe9a1377759"

    def install
      bin.install "minecraft"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mericozkayagan/minecraft/releases/download/v0.0.1/minecraft_0.0.1_linux_arm64.tar.gz"
      sha256 "2d2a0eb54c2d0add3d662ffb79dd29ae2320c5a014aa8e70226188e5657e81a3"

      def install
        bin.install "minecraft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mericozkayagan/minecraft/releases/download/v0.0.1/minecraft_0.0.1_linux_amd64.tar.gz"
      sha256 "9ab770a79f56d0fb5d6bf7f7ed8026ef1566f23113d7bfc4b26ed371fcd1eef7"

      def install
        bin.install "minecraft"
      end
    end
  end
end
