# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minecraft < Formula
  desc ""
  homepage "https://github.com/mericozkayagan/minecraft"
  version "0.1.1"

  on_macos do
    url "https://github.com/mericozkayagan/minecraft/releases/download/v0.1.1/minecraft_0.1.1_darwin_all.tar.gz"
    sha256 "62c36e4353892bcbaa2945259bd7fd61b45190ccaacba3c58505a657c52b341b"

    def install
      bin.install "minecraft"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mericozkayagan/minecraft/releases/download/v0.1.1/minecraft_0.1.1_linux_arm64.tar.gz"
      sha256 "ad3c6e817489bd29d468502670dc20c06da402cee2455ef9f8c94883824ecf28"

      def install
        bin.install "minecraft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mericozkayagan/minecraft/releases/download/v0.1.1/minecraft_0.1.1_linux_amd64.tar.gz"
      sha256 "4a690e42094c2c68298f6a54b168a1963fccba2c6ca01e6e61ac866d82fb57b7"

      def install
        bin.install "minecraft"
      end
    end
  end
end
